version: "3.7"

services:

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: wa2-group6-eureka-server
    hostname: eureka-server
    container_name: eureka-server
    ports:
      - 8761:8761
    networks:
      - wa2-group6

#  gateway:
#    build:
#      context: ./gateway
#      dockerfile: Dockerfile
#    image: wa2-group6-gateway
#    hostname: gateway
#    container_name: gateway
#    ports:
#      - 8080:8080
#    networks:
#      - wa2-group6
#    depends_on:
#      - eureka-server
#    environment:
#      # Important for clients to register with eureka
#      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
  warehouse-service:
    build:
      context: ./warehouse-service
      dockerfile: Dockerfile
    image: wa2-group6-warehouse-service
    hostname: warehouse-service
    container_name: warehouse-service
    networks:
      - wa2-group6
    expose:
      - 8100
    depends_on:
      - eureka-server
#      - gateway
    environment:
      # Important for clients to register with eureka
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
#  service2:
#    build:
#      context: ./service2
#      dockerfile: Dockerfile
#    image: wa2-group6-service2
#    hostname: service2
#    container_name: service2
#    networks:
#      - wa2-group6
#    expose:
#      - 8200
#   depends_on:
#      - eureka-server
#      - gateway
#    environment:
#      # Important for clients to register with eureka
#      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
networks:
  wa2-group6:
    driver: bridge