package it.polito.wa2.ecommerce.walletservice.domain

import it.polito.wa2.ecommerce.common.EntityBase
import it.polito.wa2.ecommerce.walletservice.client.TransactionDTO
import org.springframework.data.annotation.CreatedDate
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.ManyToOne

@Entity

class Transaction (
    @ManyToOne
    var fromWallet:Wallet?, //Will be null in case of recharges
    @ManyToOne
    var toWallet:Wallet,
    @Column(nullable=false)
    var type:TransactionType,
    @Column(nullable=false)
    @CreatedDate
    val timestamp: Long,
    @Column(nullable=false)
    val operationReference:String //TODO in case of recharge it should be autogenerated, otherwhise it should be the orderID
        ): EntityBase<Long>(){
    fun toDTO(): TransactionDTO {
        TODO("implement")
    }
}

enum class TransactionType{
    ORDER_PAYMENT,
    ORDER_REFUND,
    RECHARGE
}
