package it.polito.wa2.ecommerce.walletservice.domain

import it.polito.wa2.ecommerce.common.EntityBase
import it.polito.wa2.ecommerce.walletservice.client.transaction.TransactionDTO
import org.springframework.data.annotation.CreatedDate
import java.math.BigDecimal
import javax.persistence.Column
import javax.persistence.Entity
import javax.persistence.ManyToOne

@Entity

class Transaction (
    @ManyToOne
    var fromWallet:Wallet?, //Will be null in case of recharges
    @ManyToOne
    var toWallet:Wallet,
    @Column(nullable=false)
    var type:TransactionType,
    @Column(nullable=false)
    @CreatedDate
    val timestamp: Long,
    @Column(nullable=false)
    val amount :BigDecimal,
    @Column(nullable=false)
    val operationReference:String // in case of recharge it should be autogenerated, otherwhise it should be the orderID
        ): EntityBase<Long>(){
    fun toDTO(): TransactionDTO {
        return TransactionDTO(getId()!!,
            fromWallet?.getId().toString(),
            toWallet.getId().toString(),
            amount,
            timestamp, //TODO convert to date for frontend?
            "${type.toString()}: $operationReference"
        )
    }
}

enum class TransactionType{
    ORDER_PAYMENT,
    ORDER_REFUND,
    RECHARGE
}
