
DROP DATABASE IF EXIST mail;
CREATE DATABASE mail;

DROP DATABASE IF EXIST orders;
CREATE DATABASE  orders;

DROP DATABASE IF EXIST users;
CREATE DATABASE users;

DROP DATABASE IF EXIST wallet;
CREATE DATABASE wallet;

DROP DATABASE IF EXIST warehouse;
CREATE DATABASE warehouse ;